# Generated by Django 3.0.6 on 2020-05-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='points',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
