# Generated by Django 3.0.6 on 2020-05-31 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20200522_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Accessories', 'Accessories'), ('Books', 'Books'), ('Toys', 'Toys'), ('Stationery', 'Stationery')], default='Accessories', max_length=15),
            preserve_default=False,
        ),
    ]
