# Generated by Django 3.0.6 on 2020-05-14 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='items',
            field=models.ManyToManyField(to='market.Product'),
        ),
    ]
