# Generated by Django 3.0.6 on 2020-05-31 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('إكسسوارات', 'Accessories'), ('كتب', 'Books'), ('ألعاب', 'Toys'), ('قرطاسية', 'Stationery')], max_length=15),
        ),
    ]
