# Generated by Django 3.0.6 on 2020-05-14 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_student_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='items',
            field=models.ManyToManyField(null=True, to='market.Product'),
        ),
    ]
